#!/usr/bin/env bash

# prepare directories
mkdir -p /home/web/{{ domain }}/db
mkdir -p /home/web/{{ domain }}/uploads
mkdir -p /home/web/{{ domain }}/logs
mkdir -p /home/web/{{ domain }}/cache
mkdir -p /home/web/{{ domain }}/static
chown -R www-data:www-data /home/web/{{ domain }}

# nginx
ln -s /etc/nginx/sites-available/{{ domain }} /etc/nginx/sites-enabled/{{ domain }}
/etc/init.d/nginx reload

# supervisord
supervisorctl reread
supervisorctl add {{ package_name }}
