name: go-test-dajool
input-type: dir
pkg-type: deb
chdir: build
args:
    - etc
    - srv
config-files:
    - /etc/nginx/sites-available/go.dajool.com
    - /etc/supervisor/conf.d/go.dajool.com.conf
after-install: ./build_configs/post_install.sh
before-remove: ./build_configs/pre_uninstall.sh
dependencies:
    - supervisord
    - nginx
license: MIT
maintainer: Jochen Breuer <breuer@dajool.com>
url: http://dajool.com
deb-user: root
deb-group: root
architecture: all
description: |-
    Martini demo project.
build-vars:
    port: 3000
    debug: true
    domain: go.dajool.com
    var_path: /home/web/
    srv_path: /srv/http/
    binary_name: hello_martini
    package_name: go-test-dajool
